- moshi-sealed-codegen/src/main/kotlin/io/sweers/moshisealed/codegen/MoshiSealedProcessor.kt
- sample/build.gradle
- sample/src/test/kotlin/io/sweers/moshisealed/sample/test/MessageTest.kt
Supports defaults in code gen and adds missing error reporting. Compile tests for error messages will come in a later PR
> Finish code gen piece

- README.md
Noticed that this should probably be `implementation` instead of `kapt`, right? :)
> Tiny adjustment to README

- buildSrc/src/main/kotlin/Dependencies.kt
- ksp-test-util/src/main/kotlin/com/tschuchort/compiletesting/symbolProcessors.kt
- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/KotlinPoetSp.kt
Can't move off the copy yet due to the missing messaging wiring for reading console
> Update kotlin compile testing

- moshi-ksp/README.md
- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/KotlinPoetSp.kt
- moshi-ksp/moshi-ksp/src/test/kotlin/dev/zacsweers/moshix/ksp/JsonClassSymbolProcessorTest.kt
- moshi-ksp/tests/src/test/kotlin/dev/zacsweers/moshix/ksp/DualKotlinTest.kt
- moshi-ksp/tests/src/test/kotlin/dev/zacsweers/moshix/ksp/codegen/GeneratedAdaptersTest.kt
- moshi-sealed/codegen-ksp/src/main/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/KotlinPoetSp.kt
Now we're at feature parity with moshi's existing code gen
> Fix KSP nullability checks

- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/KspUtil.kt
- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/TargetTypes.kt
- moshi-ksp/tests/src/test/kotlin/dev/zacsweers/moshix/ksp/codegen/MoshiKspTest.kt
> Only read CLASS type supertypes

- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/AppliedType.kt
- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/KspUtil.kt
- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/TargetTypes.kt
> Refactor and clean up kotlin class detection

- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/AppliedType.kt
- moshi-ksp/tests/src/test/kotlin/dev/zacsweers/moshix/ksp/codegen/MoshiKspTest.kt
This also adds an explicit Any check to help cover checking types from other modules
> Fix supertype typename lookup

- .github/workflows/ci.yml
- .gitignore
- buildSrc/src/main/kotlin/Dependencies.kt
- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/JsonClassSymbolProcessor.kt
- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/TargetTypes.kt
Also opportunistically updates kotlinpoet and defers failing the build on errors until the end of processing
> Update KSP + use asMemberOf

- moshi-sealed/codegen-ksp/src/main/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/MoshiSealedSymbolProcessor.kt
- moshi-sealed/codegen-ksp/src/main/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/TypeCreation.kt
- moshi-sealed/codegen-ksp/src/test/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/MoshiSealedSymbolProcessorTest.kt
- moshi-sealed/codegen/src/main/kotlin/dev/zacsweers/moshix/sealed/codegen/MoshiSealedProcessor.kt
- moshi-sealed/codegen/src/test/kotlin/dev/zacsweers/moshix/sealed/codegen/MoshiSealedProcessorTest.kt
- moshi-sealed/reflect/src/main/kotlin/dev/zacsweers/moshix/sealed/reflect/MoshiSealedJsonAdapterFactory.kt
- moshi-sealed/runtime/src/main/kotlin/dev/zacsweers/moshix/sealed/annotations/TypeLabel.kt
- moshi-sealed/sample/src/main/kotlin/dev/zacsweers/moshix/sealed/sample/Message.kt
- moshi-sealed/sample/src/test/kotlin/dev/zacsweers/moshix/sealed/sample/test/MessageTest.kt
> Support alternate labels

- CHANGELOG.md
- moshi-ksp/tests/src/test/kotlin/dev/zacsweers/moshix/ksp/codegen/GeneratedAdaptersTest.kt
- moshi-ksp/tests/src/test/kotlin/dev/zacsweers/moshix/ksp/codegen/annotation/UppercaseInAnnotationPackage.kt
From https://github.com/square/moshi/pull/1287
> Port constructorParameterWithQualifierInAnnotationPackage test from Moshi

- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/shade/api/kotlintypes.kt
- moshi-ksp/tests/src/test/kotlin/dev/zacsweers/moshix/ksp/codegen/GeneratedAdaptersTest.kt
See https://github.com/square/moshi/issues/1272#issuecomment-787703904
> Fix generic arrays in code gen

- buildSrc/src/main/kotlin/Dependencies.kt
- moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/KotlinPoetSp.kt
- moshi-ksp/moshi-ksp/src/test/kotlin/dev/zacsweers/moshix/ksp/JsonClassSymbolProcessorTest.kt
- moshi-ksp/tests/src/test/kotlin/dev/zacsweers/moshix/ksp/GenericTypeAliases.kt
> Reenable JsonClassSymbolProcessorTest

- .github/workflows/ci.yml
- build.gradle.kts
- moshi-sealed/java-sealed-reflect/gradle.properties
- moshi-sealed/sealed-interfaces-samples/java/gradle.properties
Yay being able to remove the preview controls
> Update to JDK 17

- moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt
> Add moshi dependency in the gradle plugin

- moshi-ir/README.md
- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiSymbols.kt
- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/api/AdapterGenerator.kt
- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/api/PropertyGenerator.kt
- moshi-ir/moshi-compiler-plugin/src/test/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiIrVisitorTest.kt
- moshi-ir/moshi-kotlin-tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
Resolves #189. Also some more structure cleanup
> Accumulate errors

- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiIrVisitor.kt
- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/api/AdapterGenerator.kt
- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/api/PropertyGenerator.kt
- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/util/ir.kt
> Implement golden mask fast path

- moshi-ir/README.md
There is a typo in the proguard config.
> Fix moshi-ir proguard docs

- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiSymbols.kt
- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/api/DelegateKey.kt
- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/sealed/SealedAdapterGenerator.kt
This replicates moshi code gen's `TypeRenderer` impl and drops use of the stdlib's `typeOf`. This resolves #202 along the way, and also improves runtime perf a bit by just allowing us to just inline pure class refs directly.
> Render type references directly in IR

- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/api/DelegateKey.kt
- moshi-ir/moshi-kotlin-tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/CompileOnlyTests.kt
These need to just access the types param
> Fix nested type parameter type rendering

- moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt
> Pass File to gradle rather than absolute path

- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/sealed/SealedAdapterGenerator.kt
- moshi-ir/moshi-kotlin-tests/build.gradle.kts
- moshi-ir/moshi-kotlin-tests/src/test/kotlin/dev/zacsweers/moshi/sealed/MessageTest.kt
- moshi-sealed/codegen/src/main/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/MoshiSealedSymbolProcessorProvider.kt
- moshi-sealed/java-sealed-reflect/src/main/java/dev/zacsweers/moshix/sealed/java/JavaSealedJsonAdapterFactory.java
- moshi-sealed/metadata-reflect/src/main/kotlin/dev/zacsweers/moshix/sealed/reflect/MetadataMoshiSealedJsonAdapterFactory.kt
- moshi-sealed/reflect/src/main/kotlin/dev/zacsweers/moshix/sealed/reflect/MoshiSealedJsonAdapterFactory.kt
- moshi-sealed/sample/build.gradle.kts
- moshi-sealed/sample/src/test/kotlin/dev/zacsweers/moshix/sealed/sample/test/MessageTest.kt
> Fix support for non-JsonClass-annotated nested types

- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/sealed/SealedAdapterGenerator.kt
Looks like these were finally added for sealedSubclasses in 1.6
> Remove descriptor APIs in IR

- moshi-adapters/src/main/resources/META-INF/proguard/moshix-adapters.pro
There doesn't seem to be a better way to actually do this more granularly. See the comment on the rule line
> Keep AdaptedBy annotations

- moshi-metadata-reflect/src/main/kotlin/dev/zacsweers/moshix/reflect/MetadataKotlinJsonAdapterFactory.kt
- moshi-metadata-reflect/src/test/kotlin/dev/zacsweers/moshix/reflect/KotlinJsonAdapterTest.kt
> Support `@Json.ignore` in MetadataKotlinJsonAdapterFactory

- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiCommandLineProcessor.kt
- moshi-ir/moshi-compiler-plugin/src/test/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiIrVisitorTest.kt
- moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt
> Standardize options and descriptions

- moshi-sealed/codegen/src/main/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/MoshiSealedSymbolProcessorProvider.kt
- moshi-sealed/codegen/src/test/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/MoshiSealedSymbolProcessorTest.kt
> Don't use experimental-gated addAdapter with object adapters

- moshi-proguard-rule-gen/src/main/kotlin/dev/zacsweers/moshix/proguardgen/MoshiProguardGenSymbolProcessor.kt
- moshi-proguard-rule-gen/src/test/kotlin/dev/zacsweers/moshix/proguardgen/MoshiProguardGenSymbolProcessorTest.kt
> Fix proguard rule output location

- gradle/libs.versions.toml
- moshi-ir/moshi-compiler-plugin/build.gradle.kts
> Remove anvil compiler utils

- moshi-ir/moshi-gradle-plugin/build.gradle.kts
- moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt
> Fix configuration name reading in gradle

- moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt
- moshi-ir/moshi-kotlin-tests/build.gradle.kts
- moshi-ir/moshi-kotlin-tests/gradle.properties
Working around https://github.com/google/ksp/issues/1524
> Enable KSP proguard rule gen in ir tests + fix them!

- CHANGELOG.md
- moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/sealed/SealedAdapterGenerator.kt
- moshi-ir/moshi-compiler-plugin/src/test/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiIrVisitorTest.kt
- moshi-ir/moshi-kotlin-tests/src/test/kotlin/dev/zacsweers/moshi/sealed/MessageTest.kt
> Fix fallback adapter support in IR code gen not recognizing Moshi parameters to primary constructors
