moshi-sealed-codegen/src/main/kotlin/dev/zacsweers/moshisealed/codegen/MoshiSealedProcessor.kt, sample/build.gradle
This prevents consumers from having to redeclare the option
=> Reuse Moshi's generated option for convenience

moshi-sealed-codegen/src/main/kotlin/dev/zacsweers/moshisealed/codegen/MoshiSealedProcessor.kt, sample/src/test/kotlin/dev/zacsweers/moshisealed/sample/test/MessageTest.kt
Fixes #17
There might be a more idiomatic way of doing this. Definitely let me know! I've checked also how this behaves with protected and private and as far as I could see the annotation processing already fails before if those visibility modifiers are used so that is why I thought this was adequate :).
=> Use visibility of class to determine visibility of adapter

moshi-sealed/README.md, moshi-sealed/metadata-reflect/build.gradle.kts, moshi-sealed/metadata-reflect/gradle.properties, moshi-sealed/metadata-reflect/src/main/kotlin/dev/zacsweers/moshix/sealed/reflect/MetadataMoshiSealedJsonAdapterFactory.kt, moshi-sealed/metadata-reflect/src/main/resources/META-INF/com.android.tools/proguard/moshi-sealed-metadata-reflect.pro, moshi-sealed/metadata-reflect/src/main/resources/META-INF/com.android.tools/r8-from-1.6.0/moshi-sealed-metadata-reflect.pro, moshi-sealed/metadata-reflect/src/main/resources/META-INF/com.android.tools/r8-upto-1.6.0/moshi-sealed-metadata-reflect.pro, moshi-sealed/sample/build.gradle.kts, moshi-sealed/sample/src/test/kotlin/dev/zacsweers/moshix/sealed/sample/test/MessageTest.kt, moshi-sealed/sample/src/test/kotlin/dev/zacsweers/moshix/sealed/sample/test/ObjectSerializationTest.kt, moshi-sealed/sealed-interfaces-samples/kotlin/build.gradle.kts, moshi-sealed/sealed-interfaces-samples/kotlin/src/test/kotlin/dev/zacsweers/moshix/sealed/sample/interfaces/MessageTest.kt, settings.gradle.kts
This adds `:moshi-sealed:metadata-reflect` project, which is based on the `:moshi-sealed:reflect`, but uses kotlinx-metadata instead of kotlin-reflect. 
Kotlin metadata is used to check if processed class is a sealed class, and to check if a class annotated with `@DefaultObject` is an object. In other places, like obtaining annotations or object instance, Java APIs are used; couldn't find a decent way to do those things without kotlin-reflect.
Fixes #55
=> Add kotlinx-metadata based reflect artifact for Moshi Sealed

moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/shade/api/AdapterGenerator.kt, moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/shade/api/DelegateKey.kt, moshi-ksp/tests/build.gradle.kts
These don't need to run through reflection
=> Make adapters invoke constructors directly if all parameters with defaults are set

moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/shade/api/AdapterGenerator.kt
This makes it a little easier to read
=> Generate parameter name hints for readability in constructor invoke

README.md
Minor change to make it easier to navigate the the Moshi repository from the README of MoshiX
=> Add link to Moshi in Readme

moshi-ksp/README.md
It looks like there is also a `kotlin-ksp` plugin too? Not really sure what that is but I believe `com.google.devtools.ksp` is the correct one so adding it explicitly should clear the confusion. Also makes it explicit that the plugin needs to be applied in the first place.
=> Mention `com.google.devtools.ksp` in the KSP README

build.gradle.kts, moshi-ksp/extra-moshi-test-module/build.gradle.kts, moshi-ksp/extra-moshi-test-module/src/main/kotlin/dev/zacsweers/moshix/ksp/test/extra/AbstractClassInModuleA.kt, moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/KspUtil.kt, moshi-ksp/moshi-ksp/src/main/kotlin/dev/zacsweers/moshix/ksp/TargetTypes.kt, moshi-ksp/tests/build.gradle.kts, moshi-ksp/tests/src/test/kotlin/dev/zacsweers/moshix/ksp/DualKotlinTest.kt, settings.gradle.kts
Resolves #120. I think this is the right thing to do but I've also asked in the ksp channel on kotlin-lang to clarify
=> Recognize KOTLIN_LIB origins as also kotlin types

moshi-records-reflect/src/main/java/dev/zacsweers/moshix/records/RecordsJsonAdapterFactory.java, moshi-sealed/sealed-interfaces-samples/java/src/test/java/dev/zacsweers/moshix/sealed/sample/java/RecordJsonAdapterFactoryTest.java
* Constructor lookup + access
* Fix JsonQualifiers
=> Small records fixes

moshi-ir/README.md, moshi-ir/moshi-compiler-plugin/build.gradle.kts, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiCommandLineProcessor.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiComponentRegistrar.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiIrGenerationExtension.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiIrVisitor.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/proguardgen/ClassReference.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/proguardgen/CompilerUtils.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/proguardgen/FqName.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/proguardgen/KotlinPoetUtils.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/proguardgen/MoshiCompilationException.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/proguardgen/MoshiModuleDescriptor.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/proguardgen/ProguardRuleGenerationExtension.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/proguardgen/PsiUtils.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/proguardgen/RealMoshiModuleDescriptor.kt, moshi-ir/moshi-compiler-plugin/src/test/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiIrVisitorTest.kt, moshi-ir/moshi-gradle-plugin/build.gradle.kts, moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradlePluginExtension.kt, moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt
This implements generation of proguard rules. Note that these do not do any precondition checks and instead defer them to the IR transformer. This is configurable and also implements a debug option along the way.
Resolves #196, resolves #193
=> Generate proguard rules

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/TargetTypes.kt, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/api/MoshiAdapterGenerator.kt, moshi-ir/moshi-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
Was causing https://issuetracker.google.com/issues/213578515, these need to be built fresh and not just reused
=> Fix IrTypeParameters not being copied

moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt
Same principle as https://github.com/ZacSweers/redacted-compiler-plugin/pull/77. This just bit us twice.
=> Add gradle plugin as implementation not api

moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiComponentRegistrar.kt, moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt
Dealing with extension points manually appears to be problematic and we don't necessarily need to run first
=> Simplify extension adding

moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt
This way it's excluded from property inputs in KotlinCompile and doesn't break cache relocatability
=> Use FilesSubpluginOption for resources dir

gradle/libs.versions.toml, moshi-ir/moshi-compiler-plugin/api/moshi-compiler-plugin.api, moshi-ir/moshi-compiler-plugin/build.gradle.kts, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiComponentRegistrar.kt, moshi-ir/moshi-compiler-plugin/src/test/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiIrVisitorTest.kt
This switches to a maintained version of KCT and enables support for K2 in moshi-ir IFF proguard rule generation is disabled.
=> Switch to maintained KCT + support K2 in some places

gradle/libs.versions.toml, moshi-metadata-reflect/src/main/kotlin/dev/zacsweers/moshix/reflect/MetadataKotlinJsonAdapterFactory.kt, moshi-sealed/metadata-reflect/src/main/kotlin/dev/zacsweers/moshix/sealed/reflect/MetadataMoshiSealedJsonAdapterFactory.kt
Only replaced the deprecated `KotlinClassHeader` with instantiating `Metadata` directly.
=> update kotlinx-metadata-jvm to 0.6.0

moshi-sealed/runtime/src/main/resources/META-INF/proguard/moshi-sealed.pro
This ensures that the annotations themselves aren't stripped from the class descriptor and thus available at runtime.
Resolves #411
=> Keep names on `@NestedSealed` types

README.md
I recently pulled down MoshiX to do some local testing and had to have JDK 20 installed. I think that's inline with what the library catalog specifies https://github.com/ZacSweers/MoshiX/blob/4cb15346cf62955557bb06d35b05e7817c3185e4/gradle/libs.versions.toml#L20
Sorry in advance if this was an incorrect assumption!
=> remove local development section from README.md

gradle/libs.versions.toml, moshi-adapters/build.gradle.kts, moshi-immutable-adapters/README.md, moshi-immutable-adapters/api/moshi-immutable-adapters.api, moshi-immutable-adapters/build.gradle.kts, moshi-immutable-adapters/gradle.properties, moshi-immutable-adapters/src/main/kotlin/dev/zacsweers/moshix/adapters/immutable/ImmutableCollectionsJsonAdapterFactory.kt, moshi-immutable-adapters/src/test/kotlin/dev/zacsweers/moshix/adapters/immutable/ImmutableCollectionsJsonAdapterFactoryTest.kt, moshi-metadata-reflect/build.gradle.kts, settings.gradle.kts
=> Implement kotlinx immutable adapters

CHANGELOG.md, moshi-ir/moshi-compiler-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/compiler/sealed/SealedAdapterGenerator.kt, moshi-ir/moshi-compiler-plugin/src/test/kotlin/dev/zacsweers/moshix/ir/compiler/MoshiIrVisitorTest.kt, moshi-sealed/codegen/src/main/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/MoshiSealedSymbolProcessorProvider.kt, moshi-sealed/codegen/src/test/kotlin/dev/zacsweers/moshix/sealed/codegen/ksp/MoshiSealedSymbolProcessorTest.kt
=> Check for same subtypes before erroring on duplicate labels

CHANGELOG.md, moshi-proguard-rule-gen/src/main/kotlin/dev/zacsweers/moshix/proguardgen/MoshiProguardGenSymbolProcessor.kt, moshi-proguard-rule-gen/src/test/kotlin/dev/zacsweers/moshix/proguardgen/MoshiProguardGenSymbolProcessorTest.kt
=> Fix proguard rule gen not capturing non-sealed subtypes.

moshi-proguard-rule-gen/src/main/kotlin/dev/zacsweers/moshix/proguardgen/MoshiProguardGenSymbolProcessor.kt, moshi-proguard-rule-gen/src/test/kotlin/dev/zacsweers/moshix/proguardgen/MoshiProguardGenSymbolProcessorTest.kt
This PR fixes https://github.com/ZacSweers/MoshiX/issues/624. 
KotlinPoet's [ClassName](https://square.github.io/kotlinpoet/1.x/kotlinpoet/kotlinpoet/com.squareup.kotlinpoet/-class-name/index.html).toString() does not yield a valid fully qualified path for e.g. nested classes, or when backticks are used in the package name to escape [reserved keywords](https://kotlinlang.org/docs/keyword-reference.html#modifier-keywords). Instead, [`ClassName.reflectionName()`](https://square.github.io/kotlinpoet/1.x/kotlinpoet/kotlinpoet/com.squareup.kotlinpoet/-class-name/reflection-name.html) should be used for that.
☝️ This is the only functional change.
The other changes in this PR are:
- Fix the existing tests asserting incorrect expected values. These tests started failing as soon as …
=> Fix generated Proguard rules not using valid fully qualified name

.github/workflows/ci.yml, build.gradle.kts, moshi-ir/moshi-gradle-plugin/build.gradle.kts, moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/LocalProperties.kt, moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradlePluginExtension.kt, moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt, moshi-ir/moshi-kotlin-tests/build.gradle.kts, moshi-ir/moshi-kotlin-tests/gradle.properties
It is not compatible with project isolation, `providers.gradleProperty` is however.
This PR also change all build script related usages, though this isn't needed for consumers of course.
=> Replace all usages of findProperty
